import { Card } from '../redux/cardSlice';

export const deckCard: Card[] = [
  { id: 1, suit: 'Черви', rank: 6, isTrump: false },
  { id: 2, suit: 'Черви', rank: 7, isTrump: false },
  { id: 3, suit: 'Черви', rank: 8, isTrump: false },
  { id: 4, suit: 'Черви', rank: 9, isTrump: false },
  { id: 5, suit: 'Черви', rank: 10, isTrump: false },
  { id: 6, suit: 'Черви', rank: 11, isTrump: false },
  { id: 7, suit: 'Черви', rank: 12, isTrump: false },
  { id: 8, suit: 'Черви', rank: 13, isTrump: false },
  { id: 9, suit: 'Черви', rank: 14, isTrump: false },
  { id: 10, suit: 'Бубны', rank: 6, isTrump: false },
  { id: 11, suit: 'Бубны', rank: 7, isTrump: false },
  { id: 12, suit: 'Бубны', rank: 8, isTrump: false },
  { id: 13, suit: 'Бубны', rank: 9, isTrump: false },
  { id: 14, suit: 'Бубны', rank: 10, isTrump: false },
  { id: 15, suit: 'Бубны', rank: 11, isTrump: false },
  { id: 16, suit: 'Бубны', rank: 12, isTrump: false },
  { id: 17, suit: 'Бубны', rank: 13, isTrump: false },
  { id: 18, suit: 'Бубны', rank: 14, isTrump: false },
  { id: 19, suit: 'Трефы', rank: 6, isTrump: false },
  { id: 20, suit: 'Трефы', rank: 7, isTrump: false },
  { id: 21, suit: 'Трефы', rank: 8, isTrump: false },
  { id: 22, suit: 'Трефы', rank: 9, isTrump: false },
  { id: 23, suit: 'Трефы', rank: 10, isTrump: false },
  { id: 24, suit: 'Трефы', rank: 11, isTrump: false },
  { id: 25, suit: 'Трефы', rank: 12, isTrump: false },
  { id: 26, suit: 'Трефы', rank: 13, isTrump: false },
  { id: 27, suit: 'Трефы', rank: 14, isTrump: false },
  { id: 28, suit: 'Пики', rank: 6, isTrump: false },
  { id: 29, suit: 'Пики', rank: 7, isTrump: false },
  { id: 30, suit: 'Пики', rank: 8, isTrump: false },
  { id: 31, suit: 'Пики', rank: 9, isTrump: false },
  { id: 32, suit: 'Пики', rank: 10, isTrump: false },
  { id: 33, suit: 'Пики', rank: 11, isTrump: false },
  { id: 34, suit: 'Пики', rank: 12, isTrump: false },
  { id: 35, suit: 'Пики', rank: 13, isTrump: false },
  { id: 36, suit: 'Пики', rank: 14, isTrump: false },
];
